rest:
  service:
    addr: ":8080"
    timeout:
      shutdown: "30s"
      read: "0s"
      write: "0s"
      idle: "0s"
    openapi:
      ui: true
  metrics:
    enabled: true
    addr: "0.0.0.0:11190"

database:
  dsn: "host=localhost user=program password=test dbname=persons port=5432 sslmode=disable"
  max_open_conns: 10
  max_idle_conns: 5
  conn_max_lifetime: "1h"
  health_check:
    check_period: "10s"

logging:
  level: Debug
  stdout:
    level: Debug
  files:
    - path: "info.log"
      level: Info
      max_file_size: 32MB
      max_files_count: 20
      max_file_age_in_days: 15
    - path: "error.log"
      level: Error
      max_file_size: 16MB
      max_files_count: 100
      max_file_age_in_days: 90
    - path: "debug.log"
      level: Debug
      max_file_size: 16MB
      max_files_count: 100
      max_file_age_in_days: 90
  opentelemetry:
    service_name: "lab1"
    address: "0.0.0.0:4317"
    queue_size: 2048
    level: Info
