// Code generated by MockGen. DO NOT EDIT.
// Source: status_repo.go
//
// Generated by this command:
//
//	mockgen -source=status_repo.go -destination=mocks/status_provider.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dbifc "github.com/ficusinapot/ds/internal/models/dbifc"
	gomock "go.uber.org/mock/gomock"
)

// MockStatusProvider is a mock of StatusProvider interface.
type MockStatusProvider struct {
	ctrl     *gomock.Controller
	recorder *MockStatusProviderMockRecorder
	isgomock struct{}
}

// MockStatusProviderMockRecorder is the mock recorder for MockStatusProvider.
type MockStatusProviderMockRecorder struct {
	mock *MockStatusProvider
}

// NewMockStatusProvider creates a new mock instance.
func NewMockStatusProvider(ctrl *gomock.Controller) *MockStatusProvider {
	mock := &MockStatusProvider{ctrl: ctrl}
	mock.recorder = &MockStatusProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatusProvider) EXPECT() *MockStatusProviderMockRecorder {
	return m.recorder
}

// GetDBStatus mocks base method.
func (m *MockStatusProvider) GetDBStatus(ctx context.Context) dbifc.ConnectionStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDBStatus", ctx)
	ret0, _ := ret[0].(dbifc.ConnectionStatus)
	return ret0
}

// GetDBStatus indicates an expected call of GetDBStatus.
func (mr *MockStatusProviderMockRecorder) GetDBStatus(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDBStatus", reflect.TypeOf((*MockStatusProvider)(nil).GetDBStatus), ctx)
}

// IsConnectionAvailable mocks base method.
func (m *MockStatusProvider) IsConnectionAvailable(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsConnectionAvailable", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsConnectionAvailable indicates an expected call of IsConnectionAvailable.
func (mr *MockStatusProviderMockRecorder) IsConnectionAvailable(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsConnectionAvailable", reflect.TypeOf((*MockStatusProvider)(nil).IsConnectionAvailable), ctx)
}
